At/ihp10/main page
selsa-inube/ihurem-portal pull request #13
Opened 2024-11-21 19:25 UTC by Angelbt12

Crear la pagina que muestra las opciones, realizar tal cual como lo muestra el [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=102-166&node-type=canvas&t=CbOQQuAcRfrYzegx-0), mostrar datos del empleado que se alojan en el context como son:

Logo

Brand

Nombre del empleado
![image](https://github.com/user-attachments/assets/5763c9bd-1592-436c-b6fc-9ba63f3487b8)

Nota: Los datos de las opciones se consulta en otra [Tarjeta](https://inube.atlassian.net/browse/IHP-11)

Criterios de aceptación:

Debe tener las mismas medidas de mockup

Debe tener los datos de usuario del context

2024-11-22 16:41 UTC, novadeveloper14 requested changes

2024-11-22 16:41 UTC, novadeveloper14 commented on src/pages/mainPage/index.tsx
> +function MainPage() {
Change the MainPage component name to Home

2024-11-22 16:41 UTC, novadeveloper14 commented on src/App.tsx
> +      <Route path="main" element={<MainPage />} />
This page should be the one that should be shown as the home page after the session is started in no context, having a main page, the AppPage should be rendered

2024-11-22 16:41 UTC, novadeveloper14 commented on src/pages/mainPage/index.tsx
> +  const cards = [
this should go in some config

2024-11-22 16:41 UTC, novadeveloper14 commented on src/pages/mainPage/index.tsx
> +  const isTablet = useMediaQuery("(max-width: 944px)");
when we have several useMediaQuery we must use useMediaQueries

2024-11-25 12:34 UTC, Angelbt12 commented on src/pages/mainPage/index.tsx
> +  const cards = [
ok

2024-11-25 14:28 UTC, novadeveloper14 approved these changes

2024-11-25 22:11 UTC, diegoAndres01 approved these changes

2024-11-25 22:12 UTC, merged