At/ihp32/certifications request query table component
selsa-inube/ihurem-portal pull request #16
Opened 2024-11-27 02:03 UTC by Angelbt12

Realizar el componente, que muestra todas las solicitudes de certificación en tramite, como lo muestra [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=184-4123&node-type=canvas&t=C33HcLAytSt5aaFl-0)

Alcance:

La tabla debe tener todas las columnas

Los botones de eliminar y ver, no debe tener funcionamiento solo se debe visualizar los iconos

Criterios de aceptación

Se debe presentar en el storybook

Debe tener las mismas medias que el mockup

Debe mostrar mensaje si no tiene datos

Debe tener skeletonLine

2024-11-27 14:15 UTC, novadeveloper14 requested changes
Whenever another task is done in a single PR, please put it in the PR description so that we know which cards are completed upon approval.

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/config/nav.config.tsx
> +    icon: <MdVpnKey />,
We are not using this property please remove it

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/config/nav.config.tsx
> +    url: "/certifications",
We are not using this URL but it is important because with this we are going to tell the PageTitle where it has to redirect when the arrow is clicked

![image](https://github.com/user-attachments/assets/a4ba360a-a1bc-43cf-aa47-54ea7dad3329)

Taking this into account, in the AppMenu we have to replace the navigatePage of "/" with a prop that can be called in the same way. Then from src/pages/certifications/index.tsx we must pass it as navigatePage={certificationsNavConfig[0].url} with this in the future we do not have to worry so much about manipulating the code of the components but modify the url here in the configuration.

This development was made in jg/ihp18/vacations-page-assistant-request-enjoyment this branch is not in main at the moment But it is something that also has to be adjusted here.

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/interface.tsx
> +import { spacing } from "@design/tokens/spacing/spacing";
adjust imports format is wrong

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/interface.tsx
> +  appDescription?: string;
We are always leaving the optional props to the end (organization) Except when we have a function type prop, those go to the end regardless.

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/config/nav.config.tsx
> +    url: "/certifications",
Taking into account the indicated configuration, this attribute should be "/" so that when you click on the arrow it redirects to home

2024-11-27 14:15 UTC, novadeveloper14 commented on src/pages/certifications/components/CertificationsTable/usePagination.ts
To avoid a future error when implementing the configuration data please make this setting
![image](https://github.com/user-attachments/assets/572b990c-2e3c-462f-b853-aa31d84c42cf)

2024-11-27 14:15 UTC, novadeveloper14 commented on src/config/nav.tsx
>            id: "certificates",
update to "certifications" too:

![image](https://github.com/user-attachments/assets/6834b5f4-874a-4d83-92a6-9cd1a7409bd8)

2024-11-27 14:30 UTC, Angelbt12 commented on src/routes/certifications.tsx
ok

2024-11-27 14:32 UTC, Angelbt12 commented on src/pages/certifications/config/nav.config.tsx
> +    icon: <MdVpnKey />,
ok

2024-11-27 14:48 UTC, Angelbt12 commented on src/pages/certifications/config/nav.config.tsx
> +    url: "/certifications",
ok

2024-11-27 14:55 UTC, Angelbt12 commented on src/pages/certifications/interface.tsx
> +  appDescription?: string;
ok

2024-11-27 14:58 UTC, Angelbt12 commented on src/pages/certifications/config/nav.config.tsx
> +    url: "/certifications",
ok

2024-11-27 15:05 UTC, Angelbt12 commented on src/pages/certifications/components/CertificationsTable/usePagination.ts
ok

2024-11-27 21:44 UTC, novadeveloper14 approved these changes

2024-11-28 20:03 UTC, diegoAndres01 commented on src/App.tsx
Why was this validation removed?

2024-11-28 20:53 UTC, Angelbt12 commented on src/App.tsx
fue una confusión ya lo soluciono

2024-12-02 13:09 UTC, diegoAndres01 requested changes
On mobile in the menu of each record it is misplaced
![ScreenRecorderProject4](https://github.com/user-attachments/assets/73d42bd6-b2b1-452f-851d-9fce7f060299)

2024-12-03 14:38 UTC, diegoAndres01 approved these changes

2024-12-03 14:38 UTC, merged