At/ihp35/page that shows the wizard to add certification request
selsa-inube/ihurem-portal pull request #19
Opened 2024-11-27 23:51 UTC by Angelbt12

En la [pagina de solicitudes](https://inube.atlassian.net/browse/IHP-33) se muestra un botón para agregar solicitud de certificación, en esta incidencia se debe crear la pagina que se desencadena el asistido, esta debe ser tal cual como lo muestra el [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=198-4830&node-type=canvas&t=t2lrT6FsfVeuYYrp-0)

![image](https://github.com/user-attachments/assets/3e167f19-facd-4ece-8e31-4db2c4145763)

Criterios de aceptación:

La pagina se debe desencadenar del botón “Agregar Certificación“

Debe tener las misma medidas del mockup

2024-11-29 06:51 UTC, novadeveloper14 requested changes

2024-11-29 06:51 UTC, novadeveloper14 commented on src/pages/Home/home.config.tsx
The name of this folder (Home) that you created in another task was misspelled

2024-11-29 12:58 UTC, Angelbt12 commented on src/App.tsx
> -  if (employeeError) {
una confusión ya lo soluciono

2024-11-29 13:00 UTC, Angelbt12 commented on src/pages/certifications/NewCertification/index.tsx
> +function RequestNewCertification() {
It seemed more understandable to me but I fixed it anyway

2024-11-29 13:02 UTC, Angelbt12 commented on src/pages/holidays/config/nav.config.tsx
> +    url: "/",
my mistake is ok, I fixed it now it's clear to me

2024-11-29 13:25 UTC, novadeveloper14 approved these changes

2024-12-03 15:04 UTC, diegoAndres01 approved these changes

2024-12-03 15:05 UTC, merged