At/ihp11/implement options query service
selsa-inube/ihurem-portal pull request #21
Opened 2024-12-02 18:09 UTC by Angelbt12

Realizar el consumo del entpoint para obtener las opciones del empleado, si contiene opciones redirigirlo a la pagina principal, si no encuentra ninguna opción relacionada con el empleado redireccionar a pageError

![image](https://github.com/user-attachments/assets/121c4364-a978-48e9-8024-684b501bcd31)

Documentacion del servicio: http://172.106.48.22:8020/swagger/index.html#/CatalogOfOptionsForEmployeePortal/get_catalog_of_options_for_employee_portals__AC_SearchAllCatalogOfOptionsForEmployeePortals_

2024-12-03 17:06 UTC, novadeveloper14 requested changes
solve conflicts

2024-12-04 05:06 UTC, novadeveloper14 approved these changes

2024-12-05 22:39 UTC, diegoAndres01 requested changes

2024-12-06 13:23 UTC, Angelbt12 commented on src/App.tsx
> +      console.log("Opciones del empleado:", employeeOptions);
ok

2024-12-06 13:31 UTC, Angelbt12 commented on src/services/employeePortal/getOptionsConsultation/index.tsx
> +      const url = `${environment.IVITE_ISAAS_QUERY_PROCESS_SERVICE}/catalog-of-options-for-employee-portals?employeeId=${employeeId}`;
ok

2024-12-16 13:18 UTC, diegoAndres01 requested changes
When accessing the main page that displays the options, this page remains blank.
![ScreenRecorderProject10](https://github.com/user-attachments/assets/721deadc-d614-48fd-86ac-b706db55bc54)

2024-12-18 19:39 UTC, diegoAndres01 requested changes
No se están mostrando en la pagina home las opciones que se están consumiendo del entpoint
![image](https://github.com/user-attachments/assets/9da04562-e7d4-467d-98f2-3e0a34d33105)

2024-12-26 15:02 UTC, diegoAndres01 requested changes
1. Absences option is added, but it does not appear in the side menu 
![ErrorMenuLateral](https://github.com/user-attachments/assets/3254bb24-f2a5-4768-b3fa-5a16e6006b95)
2. When the page is refreshed the options are removed
![ErrorMenuOptions](https://github.com/user-attachments/assets/3893d88a-3677-4972-bd35-e26afbef94b6)

2024-12-26 19:37 UTC, diegoAndres01 requested changes
No se están mostrando las opciones que retorna el servicio: se muestran las 4 opciones, a pensar de que el servicio retorna solo tres opciones
![image](https://github.com/user-attachments/assets/41d94d6d-c641-4f75-8937-182ef2cd75bd)

remover console

![image](https://github.com/user-attachments/assets/e1027af6-670d-4f27-8620-8009b45187f6)

2024-12-27 16:17 UTC, diegoAndres01 requested changes
Unificar archivo de configuracion, debido a que se esta consultado el archivo src/config/home.config.tsx para las opciones del home y para las opciones del menu lateral se esta consultado el archivo src/config/nav.tsx

remover console.log
![image](https://github.com/user-attachments/assets/a47e24a1-1397-40a3-b28b-cc11cb07cf0f)

2024-12-30 15:19 UTC, diegoAndres01 approved these changes

2024-12-30 15:19 UTC, merged