At/ihp37/step general information
selsa-inube/ihurem-portal pull request #23
Opened 2024-12-04 12:55 UTC by Angelbt12

Se debe crear el formulario que contiene la información general de la solicitud, tal cual como esta en [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=198-4830&node-type=canvas&t=3WEOFX3bU3VY3FZX-0)

![image](https://github.com/user-attachments/assets/45e36843-68d2-4337-bdda-2c46bbf8295c)

Alcance:

Debe tener formik para las validaciones de requerido

Criterios de aceptación

Debe tener las mismas medias que el mockup

Debe mostrarse en el primer paso del asistido [tarjeta](https://inube.atlassian.net/browse/IHP-36)

Se debe mostrar los botones del asistido de siguiente deshabilitados cuando no se llena ningún campo

También se debe presentar en versión mobile

2024-12-06 06:12 UTC, novadeveloper14 requested changes
Because the implementation is very different from what is required, please check the way in which the step was implemented in the holidays assisted and replicate it in this task:

reference: https://github.com/selsa-inube/ihurem-portal/pull/22

2024-12-17 16:41 UTC, diegoAndres01 requested changes

2024-12-17 16:41 UTC, diegoAndres01 commented on package.json
> +    "@inubekit/date": "^2.39.1",
Dependency doubled

2024-12-17 16:41 UTC, diegoAndres01 commented on package.json
> +    "formik": "^2.4.6",
Dependency doubled

2024-12-17 16:41 UTC, diegoAndres01 commented on package.json
> +    "@inubekit/textarea": "^2.45.0",
Dependency doubled

2024-12-17 16:41 UTC, diegoAndres01 commented on src/pages/certifications/NewCertification/forms/GeneralInformationForm/interface.tsx
> +              options={certificationOptions}
The contract data must be obtained, with it in the context, the contract number and type must be shown,
if the employee has a contract, the input must be disabled, if the employee has more than one contract, show the select

2024-12-17 16:44 UTC, Angelbt12 commented on package.json
> +    "@inubekit/date": "^2.39.1",
ok

2024-12-17 16:44 UTC, Angelbt12 commented on package.json
> +    "@inubekit/textarea": "^2.45.0",
ok

2024-12-26 16:06 UTC, diegoAndres01 approved these changes

2024-12-26 16:06 UTC, merged