ihp21 Vacaciones: Asistido Solicitar disfrute de vacaciones paso verificación
selsa-inube/ihurem-portal pull request #25
Opened 2024-12-06 08:00 UTC by novadeveloper14

se realizo el paso de verificación para el asistido donde se muestre los datos llenos del paso uno, como lo muestra el figma

![Imagen de WhatsApp 2024-12-06 a las 02 30 47_e60ca49a](https://github.com/user-attachments/assets/3904dab5-5623-4b0e-8aa9-37a4f39dcd9e)

![Imagen de WhatsApp 2024-12-06 a las 02 35 26_0a89de3a](https://github.com/user-attachments/assets/6832a40d-a328-409c-a580-21b2095b856d)

 Criterios de aceptación

Mostrar la información que fue escrita en el paso de información general

2024-12-06 13:55 UTC, Angelbt12 approved these changes

2024-12-06 15:34 UTC, diegoAndres01 requested changes

2024-12-06 15:34 UTC, diegoAndres01 commented on src/components/cards/BoxAttribute/index.tsx
> +            appearance="dark"
The weight property is missing with the value bold

2024-12-13 21:25 UTC, diegoAndres01 requested changes
Div fill color missing

![image](https://github.com/user-attachments/assets/705b3094-ff58-4573-b502-6852e417c76b)

figma

![image](https://github.com/user-attachments/assets/db173dc5-6421-4319-acdc-ba98ca1c601f)

2024-12-17 14:27 UTC, diegoAndres01 approved these changes

2024-12-17 14:27 UTC, merged