At/ihp40/request component detail
selsa-inube/ihurem-portal pull request #27
Opened 2024-12-09 15:29 UTC by Angelbt12

Se debe crear componente del detalle de la soliciud como lo muestra el [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=184-4123&node-type=canvas&t=5uhvZpkRCWwKBD5U-0)

![image](https://github.com/user-attachments/assets/d77985f4-0f10-44c1-90b0-462e4f6b6166)

Criterios de aceptación

Debe tener las mismas medias que el mockup

Se debe presentar en el storybook

2024-12-10 08:12 UTC, novadeveloper14 requested changes

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/styles.ts
The component is too big on mobile to fit into mobile sizes which are 360px

![image](https://github.com/user-attachments/assets/536cf396-6f41-4acb-a953-ce60b4370be6)

You could follow the steps outlined in src\pages\holidays\modals\PendingHolidaysModal to comply with the measures.

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/index.tsx
> +  handleClose: () => void;
All functions must be ordered at the end

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/index.tsx
> +  handleClose,
All functions must be ordered at the end

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/index.tsx
> +export const RequestComponentDetail = ({
change for a normal function and create props const

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/stories/ComponentDetail.stories.tsx
> +import { RequestComponentDetail, IRequestComponentDetailProps } from "../index";
order imports

2024-12-10 08:12 UTC, novadeveloper14 commented on src/components/modals/ComponentDetailModal/styles.ts
> +import { spacing } from "@design/tokens/spacing/spacing";
order imports

2024-12-10 14:29 UTC, Angelbt12 commented on src/components/modals/ComponentDetailModal/styles.ts
> +import { spacing } from "@design/tokens/spacing/spacing";
ok

2024-12-10 14:29 UTC, Angelbt12 commented on src/components/modals/ComponentDetailModal/stories/ComponentDetail.stories.tsx
> +import { RequestComponentDetail, IRequestComponentDetailProps } from "../index";
ok

2024-12-10 14:38 UTC, Angelbt12 commented on src/components/modals/ComponentDetailModal/index.tsx
ok

2024-12-11 13:52 UTC, novadeveloper14 approved these changes

2024-12-16 16:54 UTC, diegoAndres01 requested changes

2024-12-16 16:54 UTC, diegoAndres01 commented on src/pages/certifications/components/CertificationsTable/index.tsx
> +  ];
The fields and title are not being displayed as shown in figma
![image](https://github.com/user-attachments/assets/dbed65d9-1a01-4b98-9e97-85b51360be26)
figma:
![image](https://github.com/user-attachments/assets/a62a74de-3655-49ce-9533-5f4e6e7134e6)

2024-12-16 17:32 UTC, Angelbt12 commented on src/pages/certifications/components/CertificationsTable/index.tsx
> +  ];
ok

2024-12-16 17:40 UTC, Angelbt12 commented on src/components/modals/ComponentDetailModal/index.tsx
> +function RequestComponentDetail({
ok

2024-12-18 13:35 UTC, diegoAndres01 requested changes
In the mobile version the modal cannot be displayed

![image](https://github.com/user-attachments/assets/83b6cdc3-af0d-4dcf-935a-0c4538c28b73)

2024-12-18 20:21 UTC, diegoAndres01 approved these changes

2024-12-18 20:21 UTC, merged