At/ihp43/modify error page
selsa-inube/ihurem-portal pull request #34
Opened 2024-12-23 16:42 UTC by Angelbt12

Ajustar pagina de error con el nuevo estilo como lo representa el [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=1-2&p=f&t=NBrh0N8i78hiFlba-0), también debe tener su versión mobile.

Ajustar pagina de error con el nuevo estilo como lo representa el [figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=1-2&p=f&t=NBrh0N8i78hiFlba-0), también debe tener su versión mobile.

2024-12-30 16:26 UTC, diegoAndres01 requested changes
Checking, the measurements found in figma are not being met, since the padding is greater than it should be, nor is the gap property so that the elements have more space between them. In addition, the phrase "© 2024 Inube" should be in bold.
![image](https://github.com/user-attachments/assets/a1563610-4baf-49e2-b873-a7a08b5a3e49)

2024-12-30 16:26 UTC, diegoAndres01 commented on src/config/errorCodes.tsx
> +export default errorCodes;
The variable name must be camelCase

2024-12-30 20:42 UTC, Angelbt12 commented on src/config/errorCodes.tsx
> +export default errorCodes;
ok

2025-01-02 14:01 UTC, diegoAndres01 requested changes
There is an error in the console
![image](https://github.com/user-attachments/assets/9d3bed83-f977-428d-9993-bceaa7301e58)
the div does not have the size of the figma

![image](https://github.com/user-attachments/assets/725996ce-e559-40b3-9272-9e16274dcae5)

2025-01-03 15:00 UTC, diegoAndres01 requested changes
Error in console 

![image](https://github.com/user-attachments/assets/d0ad7671-0a6c-46f1-bfd2-8f17db5f42f3)

2025-01-03 19:55 UTC, diegoAndres01 approved these changes

2025-01-03 19:55 UTC, merged