ihp45 Ajustar Card de Home
selsa-inube/ihurem-portal pull request #37
Opened 2024-12-31 21:24 UTC by novadeveloper14

adjust AppCard as figma mocks 
![image](https://github.com/user-attachments/assets/70a13a6c-be55-4f84-b20e-1c38cbda57f1)

2025-01-02 12:40 UTC, Angelbt12 approved these changes

2025-01-02 19:18 UTC, diegoAndres01 requested changes
Remove box when it does not have additional information

![image](https://github.com/user-attachments/assets/725c46f5-de10-4f41-a744-6b6129990b77)

replace text of each option with description as shown in figma

![image](https://github.com/user-attachments/assets/b94ee92e-3a6a-4958-abaa-c2e05d3e38f4)

figma
![image](https://github.com/user-attachments/assets/1e5c9951-0a67-4748-9972-c31511344151)

2025-01-02 19:18 UTC, diegoAndres01 commented on src/pages/home/index.tsx
> +                          complement={[
Leave optional property because some items do not have additional information

2025-01-03 20:28 UTC, diegoAndres01 requested changes
The space between the description and the detailed information in the mobile version is not the same as in figma

![image](https://github.com/user-attachments/assets/7ebc50fa-38a7-47e5-8819-1b4710463ebb)

2025-01-07 13:38 UTC, diegoAndres01 approved these changes

2025-01-07 13:38 UTC, merged