At/iph5/acceso portal
selsa-inube/ihurem-portal pull request #4
Opened 2024-11-06 12:11 UTC by Angelbt12

Esta página se despliega al inicio de la aplicación, luego de realizar las validaciones del aprovisionamiento, donde va a dar paso a si desea autenticarse o a auto registro para ingresar; También debe mostrarse en una ruta llamada  “wecolme” , la cual se debe crear en esta incidencia, se describe en mockup como debería verse: [URL de figma](https://www.figma.com/design/cpXEJp5TQdTGwVcnZ1YrIM/Employee-portal?node-id=236-23723&node-type=frame&t=71xb1seRYaiITBn3-0)

2024-11-06 17:14 UTC, diegoAndres01 commented on src/App.tsx
> +      <Route path="/welcome" element={<LoginRoutes />} />
Esta pagina se debe colocar al inicio de la aplicación, antes de la autenticación

2024-11-06 21:36 UTC, Angelbt12 commented on src/App.tsx
> +      <Route path="/welcome" element={<LoginRoutes />} />
ok

2024-11-07 12:17 UTC, diegoAndres01 requested changes
Cuando se intenta acceder a la ruta .../welcome esta mostrando el login
![incidenciaWelcome](https://github.com/user-attachments/assets/a1886b3c-f384-4b8c-9562-9827af0b1cda)


Cuando se ubica en la pagina de welcome en consola esta mostrando esta advertencia 

![image](https://github.com/user-attachments/assets/2406bdf3-fe86-4661-81b3-64db37d92d2a)

2024-11-07 16:00 UTC, diegoAndres01 approved these changes

2024-11-07 16:01 UTC, merged